"""Mudança no unique de email e phone

Revision ID: 7e10cc385631
Revises: b1483d6bd8f1
Create Date: 2022-02-11 14:06:17.664435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e10cc385631'
down_revision = 'b1483d6bd8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'leads', ['phone'])
    op.create_unique_constraint(None, 'leads', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='unique')
    op.drop_constraint(None, 'leads', type_='unique')
    # ### end Alembic commands ###
